binding.gyp
Compiling with gcc for x86_64 enables -msse and -msse2 by default, but
x86 does not. The optimized argon2 build requires SSE2, and can benefit
from SSE3.
The optimized argon2 build specifies -march=native in its makefile to
enable the highest supported instruction set. The downside is that
binaries built on newer machines may not work on older machines.
For the moment, enabling the absolute minimum seems like the safest
option.
Fixes #5
=> Enable SSE and SSE2 instructions in 32-bit build

index.js, src/argon2_node.cpp, test.spec.js
When I first starting using node-argon2, I noticed a couple issues. It turned out that you fixed them (98d639ca14818d8514b39428f2f38f7aca65c6e8, a604e2a3c30a785e13309ffaa8590c5a22acad89) before I even got a chance to file an issue, but I decided nevertheless to review the node-argon2 source to see if I could spot any further problems.
The good news is, I didn't find anything particularly worrisome. Most of the problems I found were around edge cases that I'd probably never encounter. Nevertheless, they should be fixed.
This pull request tightens up the validation done on parameters.
1. The maximum memory cost is reported as 32, but supplying the value 32 is an error. I've reduced the reported maximum to 31.
2. Input values are not checked for overflow. This means that if you supply a …
=> Tighten parameter checks

index.js, src/argon2_node.cpp
Fixes `generateSalt*` and `hash*` functions to use buffer salts instead of strings, and thus prevent a `0x00` byte to be interpreted as a null-termination of a char* string. Internally, `std::string` may have `0x00`, so this is not an issue on the C++ side.
@cgmb could you please apply your tests on this solution?
=> Fix bad salt behavior with buffers

index.js, src/argon2_node.cpp, test.spec.js
`node-argon2` currently uses null-terminated UTF-8 strings for passwords. I think that using byte buffers may be preferable. It only makes a difference in some unusual cases, but it ensures that users of node-argon2 can verify _any_ password that was hashed by argon2.
For example, consider a user who originally wrote their app in another language. Let's say they used UTF-16 encoding for passwords passed to argon2. When they later switched to node, the ability to use byte buffers would make the transition easy. As it stands, I think it would be impossible. Of course, this is a hypothetical. Maybe I'm missing something.
As you showed in a previous patch for the salt, it's easy to convert strings to buffers in JavaScript, making this change almost invisible to users passing strings. The only …
=> Use buffers for passwords

test.spec.js
We define the resulting hashes for argon2d and
argon2i in a central place and add further
asserts to the generation of the hashes.
=> add consts for hashes and test hash of argon2d

README.md
Right now, the README shows ES7 examples, but calls them ES6. This is sorta
confusing to newer developers because ES6 is available in latest Node stuff, but
you can't use ES7 features like async / await without using a transpiler like
babel currently.
This just cleans up the comments to avoid confusion.
=> Updating the readme to properly reflect ES7 features.

README.md
There is still the need to install GCC via brew on OSX, but the version of GCC is now 6.1.0.
=> Update compiler instructions to readme for OSX

index.d.ts, package.json, test-d.ts, tsconfig.json
This changelist resolves the incompatibility problems that the typescript pull request raised. After this has been merged it is safe, to use this module in a TypeScript environment. I think after this, the module's version should be changed for 1.0.0
Thank you @ranisalt  and @jdconley!
=> Proper TypeScript Support

index.d.ts, index.js, package.json, test-d.ts, test.js
Disables support for custom salt instead of cryptographic salt generator *by default*, one can always use a mocking utility (as used in tests) to force custom salts, but this makes it more cumbersome and verbose to use the lib in non recommended ways.
=> Disable usage of custom salt, use generator instead

src/argon2_node.cpp
Treating the result as a null-terminated string was truncating bytes that were
returned to the caller. Changing this to copy of the raw data fixes the
verification issues when using the resulting hash.
Fixes https://github.com/ranisalt/node-argon2/issues/107
=> removes use of strdup in hash ok callback

src/argon2_node.cpp
=> Disable anonymous namespace definition for Windows compilers

argon2.d.ts
The options interface is missing the added saltLength option from https://github.com/ranisalt/node-argon2/commit/a74d392b82f09527d24a264a86a34c03b889e569
=> Added saltLength to Options in declaration file

.travis.yml, binding.gyp, package-lock.json, package.json, src/argon2_node.cpp
[N-API](https://nodejs.org/api/n-api.html) gives ABI stability and it is VM-agnostic (doesn't bind to V8, or a specific version of V8)
Tested with `npm test`
This conversion was done with the conversion tool provided by `node-addon-api`. Then I manually went over and fixed all compilation errors and tests issues.
=> Convert to use N-API

argon2.d.ts
Declaration file is missing entry for the `needsRehash` function, added in eb1d115da02b0869945672a021dea6b9b374f7f7.
=> Added needsRehash function to declaration file

README.md
As discussed in #160, g++ versions < 5 don't seem to handle C++11 syntax very well. I think the README should be updated to reflect this new change.
=> Update README to reflect new g++ >= 5 requirement

argon2.d.ts
I need to use options with "verify" in Typescript, but they are not available here. I have added them to the function definition.
=> Added options support to the "verify" function

README.md
Hey! I think it's worth adding a note on the prebuilt binaries in the README. 
Things added:
1. New "Prebuilt Binaries" section explaining how it works and its currently supported environments.
2. Bump supported node version, from 8 to 10.
3. Added a small FAQ section below about how to manually compile the source and how to skip prebuilt binaries installation.
This should settle #245 
I'm still open for changes 👍
=> Update README about prebuilt binaries

.github/workflows/ci.yml, .github/workflows/release.yml, README.md
This should resolve #244
I also:
1. Updated README to use `node-pre-gyp` instead of `node-gyp` for rebuilding binaries.
2. Updated actions to use `npm_config_build_from_source` flag to directly build instead of ignoring scripts completely. This will prevent potential issues if dependencies rely on some post-install scripts.
=> Downgrade Ubuntu to 16.04

argon2.js, package.json, yarn.lock
Hey! 👋 
The package `node-pre-gyp` is deprecated.
It has been re-published under the `@mapbox` scope ([@mapbox/node-pre-gyp](https://github.com/mapbox/node-pre-gyp)).
Closes https://github.com/ranisalt/node-argon2/pull/274
=> feat: use @mapbox/node-pre-gyp instead of node-pre-gyp

.github/workflows/release.yml
Hi!
I've added automatic release builds for 64bit ARM architectures (such as M1 or AWS Graviton).
This uses the [uraimo/run-on-arch-action action](https://github.com/uraimo/run-on-arch-action) which runs the builds in Docker using QEMU.
It runs for both `glibc` (Ubuntu) and `musl` (Alpine) on Node v12 (for consistency with the existing builds).
The job takes about 5 mins to complete.
I've tested this in a private clone:
I believe this could help some folks with installation and CI build speeds.
Cheers!
Jan
=> Add build for arm64 (aarch64, arm/v8) for both glibc and musl

binding.gyp
This fixes the build issue introduced in 9386c96c60ee.
The output before this commit:
```
gmake: Entering directory '/usr/home/khng/.config/yarn/global/node_modules/argon2/build'
CC(target) Release/obj.target/libargon2/argon2/src/opt.o
CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
CC(target) Release/obj.target/libargon2/argon2/src/core.o
CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
CC(target) Release/obj.target/libargon2/argon2/src/thread.o
CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
AR(target) Release/obj.target/argon2.a
COPY Release/argon2.a
CXX(target) Release/obj.target/argon2/src/argon2_node.o
../src/argon2_node.cpp:52:21: error: assigning to 'uint8_t *' (aka 'unsigned char *') from 'const std::basic_string<unsigned …
```
=> Enforce C++17 on FreeBSD

argon2.js
If trying to check the password with a string that was encoded using a different algorithm, the script will correctly deserialize but then fail to destructure `params: { m, t, p, data }` as seen in this bug:
```
TypeError: Cannot read property 'm' of undefined
at Object.verify ([PATH]/node_modules/argon2/argon2.js:57:41)
at file://[PATH]/src/register.js:72:35
at processTicksAndRejections (node:internal/process/task_queues:94:5)
at async [PATH]/node_modules/server/src/join/index.js:47:23
at async [PATH]/node_modules/server/router/generic.js:28:5
at async Object.middle ([PATH]/node_modules/server/src/join/index.js:47:23) {
code: '',
params: [Object: null prototype] { '0': '' }
}
```
With this PR I'd like to start a conversation on how to fix it, my proposal is to check for the algorithm …
=> Fixed bug where a different algorithm throws

argon2.js, test/test.js
The [published RFC](https://www.rfc-editor.org/rfc/rfc9106.txt) has the following recommended options:
- If a uniformly safe option that is not tailored to your
application or hardware is acceptable, select Argon2id with t=1
iteration, p=4 lanes, m=2^(21) (2 GiB of RAM), 128-bit salt, and
256-bit tag size.  This is the FIRST RECOMMENDED option.
- If much less memory is available, a uniformly safe option is
Argon2id with t=3 iterations, p=4 lanes, m=2^(16) (64 MiB of
RAM), 128-bit salt, and 256-bit tag size.  This is the SECOND
RECOMMENDED option.
Since 2 GiB is too much for the Node engine and it will crash when allocating that much, we should adopt the second option. This will make the library safer for those that just use the defaults.
=> Update defaults to use second recommended option from RFC

package.json
Make environment variable `npm_config_argon2_binary_host_mirror` or command line `--argon2_binary_host_mirror` could work.
Fix #370
=> Rollback node-pre-gyp binary config

binding.gyp
LTO may not always work correctly, for whatever reason, resulting in e.g.
> node_modules/argon2/build/Release/argon2.node: undefined symbol: argon2_ctx
Removing LTO seems to be fine, and resolves the above issue.
=> Disable LTO to avoid missing symbols in some envs

.github/workflows/ci.yml, binding.gyp
If the environment defines flags other than `_FORTIFY_SOURCE=2` (e.g. on Arch Linux, which sets it to 3), compilation fails because the flag cannot be re-defined.
```
make: Entering directory '/tmp/node-argon2/build'
CC(target) Release/obj.target/libargon2/argon2/src/opt.o
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
CC(target) …
```
=> Avoid overriding _FORTIFY_SOURCE if already set

.github/workflows/ci.yml
Potential fix for [https://github.com/ranisalt/node-argon2/security/code-scanning/35](https://github.com/ranisalt/node-argon2/security/code-scanning/35)
To resolve the issue, we need to add a `permissions` block to the workflow. This block should explicitly define the minimal permissions required for each job or at the workflow level. Since the jobs primarily involve linting, testing, and coverage reporting, the `contents: read` permission is sufficient for most cases. For the `coverage` job, which uses a secret (`CODACY_PROJECT_TOKEN`), we need to ensure permissions are adequate for secret usage.
The permissions block will be added at the workflow root so that all jobs inherit the specified permissions unless overridden. This approach minimizes repetition and ensures uniform security …
=> Potential fix for code scanning alert no. 35: Workflow does not contain permissions
